spring:
    application:
        name: Hospital-microservice

    datasource:
        url: jdbc:postgresql://localhost:5433/mydb
        username: postgres
        password: 123

    jpa:
        hibernate:
            ddl-auto: none
        defer-datasource-initialization: true

    sql:
        init:
            schema-locations: classpath:schema.sql
            mode: always




server:
    port: 8082

eureka:
    client:
        service-url:
            defaultZone:
                http://eureka-server:8761/eureka/