spring:
    application:
        name: Timetable-microservice


    datasource:
        url: jdbc:postgresql://localhost:5433/mydb
        username: postgres
        password: 123

    sql:
        init:
            schema-locations: classpath:schema.sql
            mode: always
    jpa:
        hibernate:
            ddl-auto: none
        defer-datasource-initialization: true

server:
    port: 8083
