spring:
    application:
        name: Document-microservice

    data:
        elasticsearch:
            cluster-nodes: localhost:9200


    datasource:
        url: jdbc:postgresql://localhost:5433/mydb
        username: postgres
        password: 123

    jpa:
        hibernate:
            ddl-auto: none
        defer-datasource-initialization: true

    sql:
        init:
            schema-locations: classpath:schema.sql
            mode: always


server:
    port: 8084


